// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadWithWrite.Data;

#nullable disable

namespace ReadWithWrite.Migrations.WritingDb
{
    [DbContext(typeof(WritingDbContext))]
    [Migration("20260104145537_AddOriginalLanguageToWritingSession")]
    partial class AddOriginalLanguageToWritingSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ReadWithWrite.Models.WritingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisedText")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WritingSessions");
                });

            modelBuilder.Entity("ReadWithWrite.Models.WritingTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("WritingTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
